### ISSUE TITLE
Schema Feedback

### ISSUE THREAD

**Issue by edherm** [QuintinHull/react-app#1]
# Events
- [x] I think you may be able to eliminate the Event_User table by putting a `userId` on the Event table.
- [x] You don't have a location on the event, but you do on groups. Is this on purpose?

## Comments table
- [x] Does a user comment on a group and on an event?

**Comment by QuintinHull** [comment]
- My thought behind the Event_User table was that if the Type was doubles play there would be a total of four users. So creatorId would be the user who created the event, and then Event_User would store the users who would attend the event. If you think it would be smart to stick to just singles play would I be able to avoid the Event_Users table and just add an extra column on Event for the opponent's userId (opponentId)? I'm a little confused how I will add the functionality of adding an opponent/other user to an event.

- I thought since every Event belonged to a Group I could just grab the Location from the Group's locationId. Is that okay? Maybe I should add a more specific location for the event like which specific court.

- Thats a good point. I had planned on them being able to have a user comment on an event OR a group, but not a single comment belonging to both a group and an event. I think I will change it to only allow for comments on events.
